// Code generated by ent, DO NOT EDIT.

package monitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// MovieID applies equality check predicate on the "movie_id" field. It's identical to MovieIDEQ.
func MovieID(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldMovieID, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCode, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldTitle, v))
}

// Cover applies equality check predicate on the "cover" field. It's identical to CoverEQ.
func Cover(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCover, v))
}

// ReleaseDate applies equality check predicate on the "release_date" field. It's identical to ReleaseDateEQ.
func ReleaseDate(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldReleaseDate, v))
}

// Hash applies equality check predicate on the "hash" field. It's identical to HashEQ.
func Hash(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldHash, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldTaskID, v))
}

// NextCheckAt applies equality check predicate on the "next_check_at" field. It's identical to NextCheckAtEQ.
func NextCheckAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldNextCheckAt, v))
}

// LastCheckedAt applies equality check predicate on the "last_checked_at" field. It's identical to LastCheckedAtEQ.
func LastCheckedAt(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// Checks applies equality check predicate on the "checks" field. It's identical to ChecksEQ.
func Checks(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldChecks, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldUpdatedAt, v))
}

// MovieIDEQ applies the EQ predicate on the "movie_id" field.
func MovieIDEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldMovieID, v))
}

// MovieIDNEQ applies the NEQ predicate on the "movie_id" field.
func MovieIDNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldMovieID, v))
}

// MovieIDIn applies the In predicate on the "movie_id" field.
func MovieIDIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldMovieID, vs...))
}

// MovieIDNotIn applies the NotIn predicate on the "movie_id" field.
func MovieIDNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldMovieID, vs...))
}

// MovieIDGT applies the GT predicate on the "movie_id" field.
func MovieIDGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldMovieID, v))
}

// MovieIDGTE applies the GTE predicate on the "movie_id" field.
func MovieIDGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldMovieID, v))
}

// MovieIDLT applies the LT predicate on the "movie_id" field.
func MovieIDLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldMovieID, v))
}

// MovieIDLTE applies the LTE predicate on the "movie_id" field.
func MovieIDLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldMovieID, v))
}

// MovieIDContains applies the Contains predicate on the "movie_id" field.
func MovieIDContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldMovieID, v))
}

// MovieIDHasPrefix applies the HasPrefix predicate on the "movie_id" field.
func MovieIDHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldMovieID, v))
}

// MovieIDHasSuffix applies the HasSuffix predicate on the "movie_id" field.
func MovieIDHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldMovieID, v))
}

// MovieIDEqualFold applies the EqualFold predicate on the "movie_id" field.
func MovieIDEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldMovieID, v))
}

// MovieIDContainsFold applies the ContainsFold predicate on the "movie_id" field.
func MovieIDContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldMovieID, v))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldCode, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldTitle, v))
}

// CoverEQ applies the EQ predicate on the "cover" field.
func CoverEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldCover, v))
}

// CoverNEQ applies the NEQ predicate on the "cover" field.
func CoverNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldCover, v))
}

// CoverIn applies the In predicate on the "cover" field.
func CoverIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldCover, vs...))
}

// CoverNotIn applies the NotIn predicate on the "cover" field.
func CoverNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldCover, vs...))
}

// CoverGT applies the GT predicate on the "cover" field.
func CoverGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldCover, v))
}

// CoverGTE applies the GTE predicate on the "cover" field.
func CoverGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldCover, v))
}

// CoverLT applies the LT predicate on the "cover" field.
func CoverLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldCover, v))
}

// CoverLTE applies the LTE predicate on the "cover" field.
func CoverLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldCover, v))
}

// CoverContains applies the Contains predicate on the "cover" field.
func CoverContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldCover, v))
}

// CoverHasPrefix applies the HasPrefix predicate on the "cover" field.
func CoverHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldCover, v))
}

// CoverHasSuffix applies the HasSuffix predicate on the "cover" field.
func CoverHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldCover, v))
}

// CoverEqualFold applies the EqualFold predicate on the "cover" field.
func CoverEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldCover, v))
}

// CoverContainsFold applies the ContainsFold predicate on the "cover" field.
func CoverContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldCover, v))
}

// ReleaseDateEQ applies the EQ predicate on the "release_date" field.
func ReleaseDateEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldReleaseDate, v))
}

// ReleaseDateNEQ applies the NEQ predicate on the "release_date" field.
func ReleaseDateNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldReleaseDate, v))
}

// ReleaseDateIn applies the In predicate on the "release_date" field.
func ReleaseDateIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldReleaseDate, vs...))
}

// ReleaseDateNotIn applies the NotIn predicate on the "release_date" field.
func ReleaseDateNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldReleaseDate, vs...))
}

// ReleaseDateGT applies the GT predicate on the "release_date" field.
func ReleaseDateGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldReleaseDate, v))
}

// ReleaseDateGTE applies the GTE predicate on the "release_date" field.
func ReleaseDateGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldReleaseDate, v))
}

// ReleaseDateLT applies the LT predicate on the "release_date" field.
func ReleaseDateLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldReleaseDate, v))
}

// ReleaseDateLTE applies the LTE predicate on the "release_date" field.
func ReleaseDateLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldReleaseDate, v))
}

// ReleaseDateContains applies the Contains predicate on the "release_date" field.
func ReleaseDateContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldReleaseDate, v))
}

// ReleaseDateHasPrefix applies the HasPrefix predicate on the "release_date" field.
func ReleaseDateHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldReleaseDate, v))
}

// ReleaseDateHasSuffix applies the HasSuffix predicate on the "release_date" field.
func ReleaseDateHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldReleaseDate, v))
}

// ReleaseDateEqualFold applies the EqualFold predicate on the "release_date" field.
func ReleaseDateEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldReleaseDate, v))
}

// ReleaseDateContainsFold applies the ContainsFold predicate on the "release_date" field.
func ReleaseDateContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldReleaseDate, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldStatus, vs...))
}

// HashEQ applies the EQ predicate on the "hash" field.
func HashEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldHash, v))
}

// HashNEQ applies the NEQ predicate on the "hash" field.
func HashNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldHash, v))
}

// HashIn applies the In predicate on the "hash" field.
func HashIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldHash, vs...))
}

// HashNotIn applies the NotIn predicate on the "hash" field.
func HashNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldHash, vs...))
}

// HashGT applies the GT predicate on the "hash" field.
func HashGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldHash, v))
}

// HashGTE applies the GTE predicate on the "hash" field.
func HashGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldHash, v))
}

// HashLT applies the LT predicate on the "hash" field.
func HashLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldHash, v))
}

// HashLTE applies the LTE predicate on the "hash" field.
func HashLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldHash, v))
}

// HashContains applies the Contains predicate on the "hash" field.
func HashContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldHash, v))
}

// HashHasPrefix applies the HasPrefix predicate on the "hash" field.
func HashHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldHash, v))
}

// HashHasSuffix applies the HasSuffix predicate on the "hash" field.
func HashHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldHash, v))
}

// HashEqualFold applies the EqualFold predicate on the "hash" field.
func HashEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldHash, v))
}

// HashContainsFold applies the ContainsFold predicate on the "hash" field.
func HashContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldHash, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldTaskID))
}

// NextCheckAtEQ applies the EQ predicate on the "next_check_at" field.
func NextCheckAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldNextCheckAt, v))
}

// NextCheckAtNEQ applies the NEQ predicate on the "next_check_at" field.
func NextCheckAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldNextCheckAt, v))
}

// NextCheckAtIn applies the In predicate on the "next_check_at" field.
func NextCheckAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldNextCheckAt, vs...))
}

// NextCheckAtNotIn applies the NotIn predicate on the "next_check_at" field.
func NextCheckAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldNextCheckAt, vs...))
}

// NextCheckAtGT applies the GT predicate on the "next_check_at" field.
func NextCheckAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldNextCheckAt, v))
}

// NextCheckAtGTE applies the GTE predicate on the "next_check_at" field.
func NextCheckAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldNextCheckAt, v))
}

// NextCheckAtLT applies the LT predicate on the "next_check_at" field.
func NextCheckAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldNextCheckAt, v))
}

// NextCheckAtLTE applies the LTE predicate on the "next_check_at" field.
func NextCheckAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldNextCheckAt, v))
}

// NextCheckAtIsNil applies the IsNil predicate on the "next_check_at" field.
func NextCheckAtIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldNextCheckAt))
}

// NextCheckAtNotNil applies the NotNil predicate on the "next_check_at" field.
func NextCheckAtNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldNextCheckAt))
}

// LastCheckedAtEQ applies the EQ predicate on the "last_checked_at" field.
func LastCheckedAtEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtNEQ applies the NEQ predicate on the "last_checked_at" field.
func LastCheckedAtNEQ(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldLastCheckedAt, v))
}

// LastCheckedAtIn applies the In predicate on the "last_checked_at" field.
func LastCheckedAtIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtNotIn applies the NotIn predicate on the "last_checked_at" field.
func LastCheckedAtNotIn(vs ...time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldLastCheckedAt, vs...))
}

// LastCheckedAtGT applies the GT predicate on the "last_checked_at" field.
func LastCheckedAtGT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldLastCheckedAt, v))
}

// LastCheckedAtGTE applies the GTE predicate on the "last_checked_at" field.
func LastCheckedAtGTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldLastCheckedAt, v))
}

// LastCheckedAtLT applies the LT predicate on the "last_checked_at" field.
func LastCheckedAtLT(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldLastCheckedAt, v))
}

// LastCheckedAtLTE applies the LTE predicate on the "last_checked_at" field.
func LastCheckedAtLTE(v time.Time) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldLastCheckedAt, v))
}

// LastCheckedAtIsNil applies the IsNil predicate on the "last_checked_at" field.
func LastCheckedAtIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldLastCheckedAt))
}

// LastCheckedAtNotNil applies the NotNil predicate on the "last_checked_at" field.
func LastCheckedAtNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldLastCheckedAt))
}

// ChecksEQ applies the EQ predicate on the "checks" field.
func ChecksEQ(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldChecks, v))
}

// ChecksNEQ applies the NEQ predicate on the "checks" field.
func ChecksNEQ(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldChecks, v))
}

// ChecksIn applies the In predicate on the "checks" field.
func ChecksIn(vs ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldChecks, vs...))
}

// ChecksNotIn applies the NotIn predicate on the "checks" field.
func ChecksNotIn(vs ...int) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldChecks, vs...))
}

// ChecksGT applies the GT predicate on the "checks" field.
func ChecksGT(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldChecks, v))
}

// ChecksGTE applies the GTE predicate on the "checks" field.
func ChecksGTE(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldChecks, v))
}

// ChecksLT applies the LT predicate on the "checks" field.
func ChecksLT(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldChecks, v))
}

// ChecksLTE applies the LTE predicate on the "checks" field.
func ChecksLTE(v int) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldChecks, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Monitor {
	return predicate.Monitor(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.Monitor {
	return predicate.Monitor(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Monitor {
	return predicate.Monitor(sql.FieldContainsFold(FieldError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Monitor) predicate.Monitor {
	return predicate.Monitor(sql.NotPredicates(p))
}
