// Code generated by ent, DO NOT EDIT.

package viewedmovie

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldUpdatedAt, v))
}

// MovieID applies equality check predicate on the "movie_id" field. It's identical to MovieIDEQ.
func MovieID(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldMovieID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldUpdatedAt, v))
}

// MovieIDEQ applies the EQ predicate on the "movie_id" field.
func MovieIDEQ(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEQ(FieldMovieID, v))
}

// MovieIDNEQ applies the NEQ predicate on the "movie_id" field.
func MovieIDNEQ(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNEQ(FieldMovieID, v))
}

// MovieIDIn applies the In predicate on the "movie_id" field.
func MovieIDIn(vs ...string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldIn(FieldMovieID, vs...))
}

// MovieIDNotIn applies the NotIn predicate on the "movie_id" field.
func MovieIDNotIn(vs ...string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldNotIn(FieldMovieID, vs...))
}

// MovieIDGT applies the GT predicate on the "movie_id" field.
func MovieIDGT(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGT(FieldMovieID, v))
}

// MovieIDGTE applies the GTE predicate on the "movie_id" field.
func MovieIDGTE(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldGTE(FieldMovieID, v))
}

// MovieIDLT applies the LT predicate on the "movie_id" field.
func MovieIDLT(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLT(FieldMovieID, v))
}

// MovieIDLTE applies the LTE predicate on the "movie_id" field.
func MovieIDLTE(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldLTE(FieldMovieID, v))
}

// MovieIDContains applies the Contains predicate on the "movie_id" field.
func MovieIDContains(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldContains(FieldMovieID, v))
}

// MovieIDHasPrefix applies the HasPrefix predicate on the "movie_id" field.
func MovieIDHasPrefix(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldHasPrefix(FieldMovieID, v))
}

// MovieIDHasSuffix applies the HasSuffix predicate on the "movie_id" field.
func MovieIDHasSuffix(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldHasSuffix(FieldMovieID, v))
}

// MovieIDEqualFold applies the EqualFold predicate on the "movie_id" field.
func MovieIDEqualFold(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldEqualFold(FieldMovieID, v))
}

// MovieIDContainsFold applies the ContainsFold predicate on the "movie_id" field.
func MovieIDContainsFold(v string) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.FieldContainsFold(FieldMovieID, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ViewedMovie) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ViewedMovie) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ViewedMovie) predicate.ViewedMovie {
	return predicate.ViewedMovie(sql.NotPredicates(p))
}
