// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/favorite"
	"github.com/ppxb/miyabi/internal/ent/favoritegroup"
	"github.com/ppxb/miyabi/internal/ent/movie"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// FavoriteUpdate is the builder for updating Favorite entities.
type FavoriteUpdate struct {
	config
	hooks    []Hook
	mutation *FavoriteMutation
}

// Where appends a list predicates to the FavoriteUpdate builder.
func (_u *FavoriteUpdate) Where(ps ...predicate.Favorite) *FavoriteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FavoriteUpdate) SetUpdatedAt(v time.Time) *FavoriteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *FavoriteUpdate) SetMovieID(v int) *FavoriteUpdate {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableMovieID(v *int) *FavoriteUpdate {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *FavoriteUpdate) SetGroupID(v int) *FavoriteUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *FavoriteUpdate) SetNillableGroupID(v *int) *FavoriteUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *FavoriteUpdate) SetMovie(v *Movie) *FavoriteUpdate {
	return _u.SetMovieID(v.ID)
}

// SetGroup sets the "group" edge to the FavoriteGroup entity.
func (_u *FavoriteUpdate) SetGroup(v *FavoriteGroup) *FavoriteUpdate {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the FavoriteMutation object of the builder.
func (_u *FavoriteUpdate) Mutation() *FavoriteMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *FavoriteUpdate) ClearMovie() *FavoriteUpdate {
	_u.mutation.ClearMovie()
	return _u
}

// ClearGroup clears the "group" edge to the FavoriteGroup entity.
func (_u *FavoriteUpdate) ClearGroup() *FavoriteUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FavoriteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FavoriteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FavoriteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FavoriteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FavoriteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := favorite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FavoriteUpdate) check() error {
	if v, ok := _u.mutation.MovieID(); ok {
		if err := favorite.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Favorite.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupID(); ok {
		if err := favorite.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "Favorite.group_id": %w`, err)}
		}
	}
	if _u.mutation.MovieCleared() && len(_u.mutation.MovieIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favorite.movie"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favorite.group"`)
	}
	return nil
}

func (_u *FavoriteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(favorite.Table, favorite.Columns, sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(favorite.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.MovieTable,
			Columns: []string{favorite.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.MovieTable,
			Columns: []string{favorite.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.GroupTable,
			Columns: []string{favorite.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favoritegroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.GroupTable,
			Columns: []string{favorite.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favoritegroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FavoriteUpdateOne is the builder for updating a single Favorite entity.
type FavoriteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FavoriteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FavoriteUpdateOne) SetUpdatedAt(v time.Time) *FavoriteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *FavoriteUpdateOne) SetMovieID(v int) *FavoriteUpdateOne {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableMovieID(v *int) *FavoriteUpdateOne {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *FavoriteUpdateOne) SetGroupID(v int) *FavoriteUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *FavoriteUpdateOne) SetNillableGroupID(v *int) *FavoriteUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetMovie sets the "movie" edge to the Movie entity.
func (_u *FavoriteUpdateOne) SetMovie(v *Movie) *FavoriteUpdateOne {
	return _u.SetMovieID(v.ID)
}

// SetGroup sets the "group" edge to the FavoriteGroup entity.
func (_u *FavoriteUpdateOne) SetGroup(v *FavoriteGroup) *FavoriteUpdateOne {
	return _u.SetGroupID(v.ID)
}

// Mutation returns the FavoriteMutation object of the builder.
func (_u *FavoriteUpdateOne) Mutation() *FavoriteMutation {
	return _u.mutation
}

// ClearMovie clears the "movie" edge to the Movie entity.
func (_u *FavoriteUpdateOne) ClearMovie() *FavoriteUpdateOne {
	_u.mutation.ClearMovie()
	return _u
}

// ClearGroup clears the "group" edge to the FavoriteGroup entity.
func (_u *FavoriteUpdateOne) ClearGroup() *FavoriteUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// Where appends a list predicates to the FavoriteUpdate builder.
func (_u *FavoriteUpdateOne) Where(ps ...predicate.Favorite) *FavoriteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FavoriteUpdateOne) Select(field string, fields ...string) *FavoriteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Favorite entity.
func (_u *FavoriteUpdateOne) Save(ctx context.Context) (*Favorite, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FavoriteUpdateOne) SaveX(ctx context.Context) *Favorite {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FavoriteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FavoriteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FavoriteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := favorite.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FavoriteUpdateOne) check() error {
	if v, ok := _u.mutation.MovieID(); ok {
		if err := favorite.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Favorite.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupID(); ok {
		if err := favorite.GroupIDValidator(v); err != nil {
			return &ValidationError{Name: "group_id", err: fmt.Errorf(`ent: validator failed for field "Favorite.group_id": %w`, err)}
		}
	}
	if _u.mutation.MovieCleared() && len(_u.mutation.MovieIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favorite.movie"`)
	}
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Favorite.group"`)
	}
	return nil
}

func (_u *FavoriteUpdateOne) sqlSave(ctx context.Context) (_node *Favorite, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(favorite.Table, favorite.Columns, sqlgraph.NewFieldSpec(favorite.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Favorite.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, favorite.FieldID)
		for _, f := range fields {
			if !favorite.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != favorite.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(favorite.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.MovieCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.MovieTable,
			Columns: []string{favorite.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MovieIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.MovieTable,
			Columns: []string{favorite.MovieColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(movie.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.GroupTable,
			Columns: []string{favorite.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favoritegroup.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   favorite.GroupTable,
			Columns: []string{favorite.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(favoritegroup.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Favorite{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{favorite.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
