// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/favoritegroup"
)

// FavoriteGroup is the model entity for the FavoriteGroup schema.
type FavoriteGroup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FavoriteGroupQuery when eager-loading is set.
	Edges        FavoriteGroupEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FavoriteGroupEdges holds the relations/edges for other nodes in the graph.
type FavoriteGroupEdges struct {
	// Favorites holds the value of the favorites edge.
	Favorites []*Favorite `json:"favorites,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// FavoritesOrErr returns the Favorites value or an error if the edge
// was not loaded in eager-loading.
func (e FavoriteGroupEdges) FavoritesOrErr() ([]*Favorite, error) {
	if e.loadedTypes[0] {
		return e.Favorites, nil
	}
	return nil, &NotLoadedError{edge: "favorites"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FavoriteGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case favoritegroup.FieldID:
			values[i] = new(sql.NullInt64)
		case favoritegroup.FieldName:
			values[i] = new(sql.NullString)
		case favoritegroup.FieldCreatedAt, favoritegroup.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FavoriteGroup fields.
func (_m *FavoriteGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case favoritegroup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case favoritegroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case favoritegroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case favoritegroup.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FavoriteGroup.
// This includes values selected through modifiers, order, etc.
func (_m *FavoriteGroup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFavorites queries the "favorites" edge of the FavoriteGroup entity.
func (_m *FavoriteGroup) QueryFavorites() *FavoriteQuery {
	return NewFavoriteGroupClient(_m.config).QueryFavorites(_m)
}

// Update returns a builder for updating this FavoriteGroup.
// Note that you need to call FavoriteGroup.Unwrap() before calling this method if this FavoriteGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FavoriteGroup) Update() *FavoriteGroupUpdateOne {
	return NewFavoriteGroupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FavoriteGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FavoriteGroup) Unwrap() *FavoriteGroup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FavoriteGroup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FavoriteGroup) String() string {
	var builder strings.Builder
	builder.WriteString("FavoriteGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteByte(')')
	return builder.String()
}

// FavoriteGroups is a parsable slice of FavoriteGroup.
type FavoriteGroups []*FavoriteGroup
