// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/monitor"
	"github.com/ppxb/miyabi/internal/ent/predicate"
)

// MonitorUpdate is the builder for updating Monitor entities.
type MonitorUpdate struct {
	config
	hooks    []Hook
	mutation *MonitorMutation
}

// Where appends a list predicates to the MonitorUpdate builder.
func (_u *MonitorUpdate) Where(ps ...predicate.Monitor) *MonitorUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MonitorUpdate) SetUpdatedAt(v time.Time) *MonitorUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *MonitorUpdate) SetMovieID(v string) *MonitorUpdate {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableMovieID(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *MonitorUpdate) SetCode(v string) *MonitorUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableCode(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MonitorUpdate) SetTitle(v string) *MonitorUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableTitle(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *MonitorUpdate) SetCover(v string) *MonitorUpdate {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableCover(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *MonitorUpdate) SetReleaseDate(v string) *MonitorUpdate {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableReleaseDate(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MonitorUpdate) SetStatus(v monitor.Status) *MonitorUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableStatus(v *monitor.Status) *MonitorUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *MonitorUpdate) SetHash(v string) *MonitorUpdate {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableHash(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *MonitorUpdate) SetTaskID(v int) *MonitorUpdate {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableTaskID(v *int) *MonitorUpdate {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *MonitorUpdate) AddTaskID(v int) *MonitorUpdate {
	_u.mutation.AddTaskID(v)
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *MonitorUpdate) ClearTaskID() *MonitorUpdate {
	_u.mutation.ClearTaskID()
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *MonitorUpdate) SetNextCheckAt(v time.Time) *MonitorUpdate {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableNextCheckAt(v *time.Time) *MonitorUpdate {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (_u *MonitorUpdate) ClearNextCheckAt() *MonitorUpdate {
	_u.mutation.ClearNextCheckAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *MonitorUpdate) SetLastCheckedAt(v time.Time) *MonitorUpdate {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableLastCheckedAt(v *time.Time) *MonitorUpdate {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *MonitorUpdate) ClearLastCheckedAt() *MonitorUpdate {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetChecks sets the "checks" field.
func (_u *MonitorUpdate) SetChecks(v int) *MonitorUpdate {
	_u.mutation.ResetChecks()
	_u.mutation.SetChecks(v)
	return _u
}

// SetNillableChecks sets the "checks" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableChecks(v *int) *MonitorUpdate {
	if v != nil {
		_u.SetChecks(*v)
	}
	return _u
}

// AddChecks adds value to the "checks" field.
func (_u *MonitorUpdate) AddChecks(v int) *MonitorUpdate {
	_u.mutation.AddChecks(v)
	return _u
}

// SetError sets the "error" field.
func (_u *MonitorUpdate) SetError(v string) *MonitorUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *MonitorUpdate) SetNillableError(v *string) *MonitorUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *MonitorUpdate) ClearError() *MonitorUpdate {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the MonitorMutation object of the builder.
func (_u *MonitorUpdate) Mutation() *MonitorMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *MonitorUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *MonitorUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MonitorUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := monitor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MonitorUpdate) check() error {
	if v, ok := _u.mutation.MovieID(); ok {
		if err := monitor.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Monitor.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := monitor.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Monitor.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := monitor.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Monitor.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checks(); ok {
		if err := monitor.ChecksValidator(v); err != nil {
			return &ValidationError{Name: "checks", err: fmt.Errorf(`ent: validator failed for field "Monitor.checks": %w`, err)}
		}
	}
	return nil
}

func (_u *MonitorUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitor.Table, monitor.Columns, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(monitor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MovieID(); ok {
		_spec.SetField(monitor.FieldMovieID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(monitor.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(monitor.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(monitor.FieldCover, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(monitor.FieldReleaseDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(monitor.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(monitor.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(monitor.FieldTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(monitor.FieldTaskID, field.TypeInt, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(monitor.FieldTaskID, field.TypeInt)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(monitor.FieldNextCheckAt, field.TypeTime, value)
	}
	if _u.mutation.NextCheckAtCleared() {
		_spec.ClearField(monitor.FieldNextCheckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(monitor.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(monitor.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Checks(); ok {
		_spec.SetField(monitor.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecks(); ok {
		_spec.AddField(monitor.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(monitor.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(monitor.FieldError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// MonitorUpdateOne is the builder for updating a single Monitor entity.
type MonitorUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonitorMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *MonitorUpdateOne) SetUpdatedAt(v time.Time) *MonitorUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetMovieID sets the "movie_id" field.
func (_u *MonitorUpdateOne) SetMovieID(v string) *MonitorUpdateOne {
	_u.mutation.SetMovieID(v)
	return _u
}

// SetNillableMovieID sets the "movie_id" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableMovieID(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetMovieID(*v)
	}
	return _u
}

// SetCode sets the "code" field.
func (_u *MonitorUpdateOne) SetCode(v string) *MonitorUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableCode(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *MonitorUpdateOne) SetTitle(v string) *MonitorUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableTitle(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCover sets the "cover" field.
func (_u *MonitorUpdateOne) SetCover(v string) *MonitorUpdateOne {
	_u.mutation.SetCover(v)
	return _u
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableCover(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetCover(*v)
	}
	return _u
}

// SetReleaseDate sets the "release_date" field.
func (_u *MonitorUpdateOne) SetReleaseDate(v string) *MonitorUpdateOne {
	_u.mutation.SetReleaseDate(v)
	return _u
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableReleaseDate(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetReleaseDate(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *MonitorUpdateOne) SetStatus(v monitor.Status) *MonitorUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableStatus(v *monitor.Status) *MonitorUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetHash sets the "hash" field.
func (_u *MonitorUpdateOne) SetHash(v string) *MonitorUpdateOne {
	_u.mutation.SetHash(v)
	return _u
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableHash(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetHash(*v)
	}
	return _u
}

// SetTaskID sets the "task_id" field.
func (_u *MonitorUpdateOne) SetTaskID(v int) *MonitorUpdateOne {
	_u.mutation.ResetTaskID()
	_u.mutation.SetTaskID(v)
	return _u
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableTaskID(v *int) *MonitorUpdateOne {
	if v != nil {
		_u.SetTaskID(*v)
	}
	return _u
}

// AddTaskID adds value to the "task_id" field.
func (_u *MonitorUpdateOne) AddTaskID(v int) *MonitorUpdateOne {
	_u.mutation.AddTaskID(v)
	return _u
}

// ClearTaskID clears the value of the "task_id" field.
func (_u *MonitorUpdateOne) ClearTaskID() *MonitorUpdateOne {
	_u.mutation.ClearTaskID()
	return _u
}

// SetNextCheckAt sets the "next_check_at" field.
func (_u *MonitorUpdateOne) SetNextCheckAt(v time.Time) *MonitorUpdateOne {
	_u.mutation.SetNextCheckAt(v)
	return _u
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableNextCheckAt(v *time.Time) *MonitorUpdateOne {
	if v != nil {
		_u.SetNextCheckAt(*v)
	}
	return _u
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (_u *MonitorUpdateOne) ClearNextCheckAt() *MonitorUpdateOne {
	_u.mutation.ClearNextCheckAt()
	return _u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_u *MonitorUpdateOne) SetLastCheckedAt(v time.Time) *MonitorUpdateOne {
	_u.mutation.SetLastCheckedAt(v)
	return _u
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableLastCheckedAt(v *time.Time) *MonitorUpdateOne {
	if v != nil {
		_u.SetLastCheckedAt(*v)
	}
	return _u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (_u *MonitorUpdateOne) ClearLastCheckedAt() *MonitorUpdateOne {
	_u.mutation.ClearLastCheckedAt()
	return _u
}

// SetChecks sets the "checks" field.
func (_u *MonitorUpdateOne) SetChecks(v int) *MonitorUpdateOne {
	_u.mutation.ResetChecks()
	_u.mutation.SetChecks(v)
	return _u
}

// SetNillableChecks sets the "checks" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableChecks(v *int) *MonitorUpdateOne {
	if v != nil {
		_u.SetChecks(*v)
	}
	return _u
}

// AddChecks adds value to the "checks" field.
func (_u *MonitorUpdateOne) AddChecks(v int) *MonitorUpdateOne {
	_u.mutation.AddChecks(v)
	return _u
}

// SetError sets the "error" field.
func (_u *MonitorUpdateOne) SetError(v string) *MonitorUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *MonitorUpdateOne) SetNillableError(v *string) *MonitorUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *MonitorUpdateOne) ClearError() *MonitorUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// Mutation returns the MonitorMutation object of the builder.
func (_u *MonitorUpdateOne) Mutation() *MonitorMutation {
	return _u.mutation
}

// Where appends a list predicates to the MonitorUpdate builder.
func (_u *MonitorUpdateOne) Where(ps ...predicate.Monitor) *MonitorUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *MonitorUpdateOne) Select(field string, fields ...string) *MonitorUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Monitor entity.
func (_u *MonitorUpdateOne) Save(ctx context.Context) (*Monitor, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *MonitorUpdateOne) SaveX(ctx context.Context) *Monitor {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *MonitorUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *MonitorUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *MonitorUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := monitor.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *MonitorUpdateOne) check() error {
	if v, ok := _u.mutation.MovieID(); ok {
		if err := monitor.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Monitor.movie_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Code(); ok {
		if err := monitor.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Monitor.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := monitor.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Monitor.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Checks(); ok {
		if err := monitor.ChecksValidator(v); err != nil {
			return &ValidationError{Name: "checks", err: fmt.Errorf(`ent: validator failed for field "Monitor.checks": %w`, err)}
		}
	}
	return nil
}

func (_u *MonitorUpdateOne) sqlSave(ctx context.Context) (_node *Monitor, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitor.Table, monitor.Columns, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Monitor.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitor.FieldID)
		for _, f := range fields {
			if !monitor.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitor.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(monitor.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MovieID(); ok {
		_spec.SetField(monitor.FieldMovieID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(monitor.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(monitor.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cover(); ok {
		_spec.SetField(monitor.FieldCover, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReleaseDate(); ok {
		_spec.SetField(monitor.FieldReleaseDate, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(monitor.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Hash(); ok {
		_spec.SetField(monitor.FieldHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.TaskID(); ok {
		_spec.SetField(monitor.FieldTaskID, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTaskID(); ok {
		_spec.AddField(monitor.FieldTaskID, field.TypeInt, value)
	}
	if _u.mutation.TaskIDCleared() {
		_spec.ClearField(monitor.FieldTaskID, field.TypeInt)
	}
	if value, ok := _u.mutation.NextCheckAt(); ok {
		_spec.SetField(monitor.FieldNextCheckAt, field.TypeTime, value)
	}
	if _u.mutation.NextCheckAtCleared() {
		_spec.ClearField(monitor.FieldNextCheckAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCheckedAt(); ok {
		_spec.SetField(monitor.FieldLastCheckedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCheckedAtCleared() {
		_spec.ClearField(monitor.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Checks(); ok {
		_spec.SetField(monitor.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedChecks(); ok {
		_spec.AddField(monitor.FieldChecks, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(monitor.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(monitor.FieldError, field.TypeString)
	}
	_node = &Monitor{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitor.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
