// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ppxb/miyabi/internal/ent/monitor"
)

// MonitorCreate is the builder for creating a Monitor entity.
type MonitorCreate struct {
	config
	mutation *MonitorMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *MonitorCreate) SetCreatedAt(v time.Time) *MonitorCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableCreatedAt(v *time.Time) *MonitorCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *MonitorCreate) SetUpdatedAt(v time.Time) *MonitorCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableUpdatedAt(v *time.Time) *MonitorCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetMovieID sets the "movie_id" field.
func (_c *MonitorCreate) SetMovieID(v string) *MonitorCreate {
	_c.mutation.SetMovieID(v)
	return _c
}

// SetCode sets the "code" field.
func (_c *MonitorCreate) SetCode(v string) *MonitorCreate {
	_c.mutation.SetCode(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *MonitorCreate) SetTitle(v string) *MonitorCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableTitle(v *string) *MonitorCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetCover sets the "cover" field.
func (_c *MonitorCreate) SetCover(v string) *MonitorCreate {
	_c.mutation.SetCover(v)
	return _c
}

// SetNillableCover sets the "cover" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableCover(v *string) *MonitorCreate {
	if v != nil {
		_c.SetCover(*v)
	}
	return _c
}

// SetReleaseDate sets the "release_date" field.
func (_c *MonitorCreate) SetReleaseDate(v string) *MonitorCreate {
	_c.mutation.SetReleaseDate(v)
	return _c
}

// SetNillableReleaseDate sets the "release_date" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableReleaseDate(v *string) *MonitorCreate {
	if v != nil {
		_c.SetReleaseDate(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *MonitorCreate) SetStatus(v monitor.Status) *MonitorCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableStatus(v *monitor.Status) *MonitorCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetHash sets the "hash" field.
func (_c *MonitorCreate) SetHash(v string) *MonitorCreate {
	_c.mutation.SetHash(v)
	return _c
}

// SetNillableHash sets the "hash" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableHash(v *string) *MonitorCreate {
	if v != nil {
		_c.SetHash(*v)
	}
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *MonitorCreate) SetTaskID(v int) *MonitorCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetNillableTaskID sets the "task_id" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableTaskID(v *int) *MonitorCreate {
	if v != nil {
		_c.SetTaskID(*v)
	}
	return _c
}

// SetNextCheckAt sets the "next_check_at" field.
func (_c *MonitorCreate) SetNextCheckAt(v time.Time) *MonitorCreate {
	_c.mutation.SetNextCheckAt(v)
	return _c
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableNextCheckAt(v *time.Time) *MonitorCreate {
	if v != nil {
		_c.SetNextCheckAt(*v)
	}
	return _c
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (_c *MonitorCreate) SetLastCheckedAt(v time.Time) *MonitorCreate {
	_c.mutation.SetLastCheckedAt(v)
	return _c
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableLastCheckedAt(v *time.Time) *MonitorCreate {
	if v != nil {
		_c.SetLastCheckedAt(*v)
	}
	return _c
}

// SetChecks sets the "checks" field.
func (_c *MonitorCreate) SetChecks(v int) *MonitorCreate {
	_c.mutation.SetChecks(v)
	return _c
}

// SetNillableChecks sets the "checks" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableChecks(v *int) *MonitorCreate {
	if v != nil {
		_c.SetChecks(*v)
	}
	return _c
}

// SetError sets the "error" field.
func (_c *MonitorCreate) SetError(v string) *MonitorCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *MonitorCreate) SetNillableError(v *string) *MonitorCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// Mutation returns the MonitorMutation object of the builder.
func (_c *MonitorCreate) Mutation() *MonitorMutation {
	return _c.mutation
}

// Save creates the Monitor in the database.
func (_c *MonitorCreate) Save(ctx context.Context) (*Monitor, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MonitorCreate) SaveX(ctx context.Context) *Monitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MonitorCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := monitor.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := monitor.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Title(); !ok {
		v := monitor.DefaultTitle
		_c.mutation.SetTitle(v)
	}
	if _, ok := _c.mutation.Cover(); !ok {
		v := monitor.DefaultCover
		_c.mutation.SetCover(v)
	}
	if _, ok := _c.mutation.ReleaseDate(); !ok {
		v := monitor.DefaultReleaseDate
		_c.mutation.SetReleaseDate(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := monitor.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Hash(); !ok {
		v := monitor.DefaultHash
		_c.mutation.SetHash(v)
	}
	if _, ok := _c.mutation.Checks(); !ok {
		v := monitor.DefaultChecks
		_c.mutation.SetChecks(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MonitorCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Monitor.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Monitor.updated_at"`)}
	}
	if _, ok := _c.mutation.MovieID(); !ok {
		return &ValidationError{Name: "movie_id", err: errors.New(`ent: missing required field "Monitor.movie_id"`)}
	}
	if v, ok := _c.mutation.MovieID(); ok {
		if err := monitor.MovieIDValidator(v); err != nil {
			return &ValidationError{Name: "movie_id", err: fmt.Errorf(`ent: validator failed for field "Monitor.movie_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Monitor.code"`)}
	}
	if v, ok := _c.mutation.Code(); ok {
		if err := monitor.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Monitor.code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "Monitor.title"`)}
	}
	if _, ok := _c.mutation.Cover(); !ok {
		return &ValidationError{Name: "cover", err: errors.New(`ent: missing required field "Monitor.cover"`)}
	}
	if _, ok := _c.mutation.ReleaseDate(); !ok {
		return &ValidationError{Name: "release_date", err: errors.New(`ent: missing required field "Monitor.release_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Monitor.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := monitor.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Monitor.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Hash(); !ok {
		return &ValidationError{Name: "hash", err: errors.New(`ent: missing required field "Monitor.hash"`)}
	}
	if _, ok := _c.mutation.Checks(); !ok {
		return &ValidationError{Name: "checks", err: errors.New(`ent: missing required field "Monitor.checks"`)}
	}
	if v, ok := _c.mutation.Checks(); ok {
		if err := monitor.ChecksValidator(v); err != nil {
			return &ValidationError{Name: "checks", err: fmt.Errorf(`ent: validator failed for field "Monitor.checks": %w`, err)}
		}
	}
	return nil
}

func (_c *MonitorCreate) sqlSave(ctx context.Context) (*Monitor, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MonitorCreate) createSpec() (*Monitor, *sqlgraph.CreateSpec) {
	var (
		_node = &Monitor{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(monitor.Table, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(monitor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(monitor.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.MovieID(); ok {
		_spec.SetField(monitor.FieldMovieID, field.TypeString, value)
		_node.MovieID = value
	}
	if value, ok := _c.mutation.Code(); ok {
		_spec.SetField(monitor.FieldCode, field.TypeString, value)
		_node.Code = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(monitor.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Cover(); ok {
		_spec.SetField(monitor.FieldCover, field.TypeString, value)
		_node.Cover = value
	}
	if value, ok := _c.mutation.ReleaseDate(); ok {
		_spec.SetField(monitor.FieldReleaseDate, field.TypeString, value)
		_node.ReleaseDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(monitor.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Hash(); ok {
		_spec.SetField(monitor.FieldHash, field.TypeString, value)
		_node.Hash = value
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(monitor.FieldTaskID, field.TypeInt, value)
		_node.TaskID = &value
	}
	if value, ok := _c.mutation.NextCheckAt(); ok {
		_spec.SetField(monitor.FieldNextCheckAt, field.TypeTime, value)
		_node.NextCheckAt = &value
	}
	if value, ok := _c.mutation.LastCheckedAt(); ok {
		_spec.SetField(monitor.FieldLastCheckedAt, field.TypeTime, value)
		_node.LastCheckedAt = &value
	}
	if value, ok := _c.mutation.Checks(); ok {
		_spec.SetField(monitor.FieldChecks, field.TypeInt, value)
		_node.Checks = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(monitor.FieldError, field.TypeString, value)
		_node.Error = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Monitor.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MonitorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MonitorCreate) OnConflict(opts ...sql.ConflictOption) *MonitorUpsertOne {
	_c.conflict = opts
	return &MonitorUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MonitorCreate) OnConflictColumns(columns ...string) *MonitorUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MonitorUpsertOne{
		create: _c,
	}
}

type (
	// MonitorUpsertOne is the builder for "upsert"-ing
	//  one Monitor node.
	MonitorUpsertOne struct {
		create *MonitorCreate
	}

	// MonitorUpsert is the "OnConflict" setter.
	MonitorUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *MonitorUpsert) SetUpdatedAt(v time.Time) *MonitorUpsert {
	u.Set(monitor.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateUpdatedAt() *MonitorUpsert {
	u.SetExcluded(monitor.FieldUpdatedAt)
	return u
}

// SetMovieID sets the "movie_id" field.
func (u *MonitorUpsert) SetMovieID(v string) *MonitorUpsert {
	u.Set(monitor.FieldMovieID, v)
	return u
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateMovieID() *MonitorUpsert {
	u.SetExcluded(monitor.FieldMovieID)
	return u
}

// SetCode sets the "code" field.
func (u *MonitorUpsert) SetCode(v string) *MonitorUpsert {
	u.Set(monitor.FieldCode, v)
	return u
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateCode() *MonitorUpsert {
	u.SetExcluded(monitor.FieldCode)
	return u
}

// SetTitle sets the "title" field.
func (u *MonitorUpsert) SetTitle(v string) *MonitorUpsert {
	u.Set(monitor.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateTitle() *MonitorUpsert {
	u.SetExcluded(monitor.FieldTitle)
	return u
}

// SetCover sets the "cover" field.
func (u *MonitorUpsert) SetCover(v string) *MonitorUpsert {
	u.Set(monitor.FieldCover, v)
	return u
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateCover() *MonitorUpsert {
	u.SetExcluded(monitor.FieldCover)
	return u
}

// SetReleaseDate sets the "release_date" field.
func (u *MonitorUpsert) SetReleaseDate(v string) *MonitorUpsert {
	u.Set(monitor.FieldReleaseDate, v)
	return u
}

// UpdateReleaseDate sets the "release_date" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateReleaseDate() *MonitorUpsert {
	u.SetExcluded(monitor.FieldReleaseDate)
	return u
}

// SetStatus sets the "status" field.
func (u *MonitorUpsert) SetStatus(v monitor.Status) *MonitorUpsert {
	u.Set(monitor.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateStatus() *MonitorUpsert {
	u.SetExcluded(monitor.FieldStatus)
	return u
}

// SetHash sets the "hash" field.
func (u *MonitorUpsert) SetHash(v string) *MonitorUpsert {
	u.Set(monitor.FieldHash, v)
	return u
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateHash() *MonitorUpsert {
	u.SetExcluded(monitor.FieldHash)
	return u
}

// SetTaskID sets the "task_id" field.
func (u *MonitorUpsert) SetTaskID(v int) *MonitorUpsert {
	u.Set(monitor.FieldTaskID, v)
	return u
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateTaskID() *MonitorUpsert {
	u.SetExcluded(monitor.FieldTaskID)
	return u
}

// AddTaskID adds v to the "task_id" field.
func (u *MonitorUpsert) AddTaskID(v int) *MonitorUpsert {
	u.Add(monitor.FieldTaskID, v)
	return u
}

// ClearTaskID clears the value of the "task_id" field.
func (u *MonitorUpsert) ClearTaskID() *MonitorUpsert {
	u.SetNull(monitor.FieldTaskID)
	return u
}

// SetNextCheckAt sets the "next_check_at" field.
func (u *MonitorUpsert) SetNextCheckAt(v time.Time) *MonitorUpsert {
	u.Set(monitor.FieldNextCheckAt, v)
	return u
}

// UpdateNextCheckAt sets the "next_check_at" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateNextCheckAt() *MonitorUpsert {
	u.SetExcluded(monitor.FieldNextCheckAt)
	return u
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (u *MonitorUpsert) ClearNextCheckAt() *MonitorUpsert {
	u.SetNull(monitor.FieldNextCheckAt)
	return u
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *MonitorUpsert) SetLastCheckedAt(v time.Time) *MonitorUpsert {
	u.Set(monitor.FieldLastCheckedAt, v)
	return u
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateLastCheckedAt() *MonitorUpsert {
	u.SetExcluded(monitor.FieldLastCheckedAt)
	return u
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *MonitorUpsert) ClearLastCheckedAt() *MonitorUpsert {
	u.SetNull(monitor.FieldLastCheckedAt)
	return u
}

// SetChecks sets the "checks" field.
func (u *MonitorUpsert) SetChecks(v int) *MonitorUpsert {
	u.Set(monitor.FieldChecks, v)
	return u
}

// UpdateChecks sets the "checks" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateChecks() *MonitorUpsert {
	u.SetExcluded(monitor.FieldChecks)
	return u
}

// AddChecks adds v to the "checks" field.
func (u *MonitorUpsert) AddChecks(v int) *MonitorUpsert {
	u.Add(monitor.FieldChecks, v)
	return u
}

// SetError sets the "error" field.
func (u *MonitorUpsert) SetError(v string) *MonitorUpsert {
	u.Set(monitor.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *MonitorUpsert) UpdateError() *MonitorUpsert {
	u.SetExcluded(monitor.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *MonitorUpsert) ClearError() *MonitorUpsert {
	u.SetNull(monitor.FieldError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MonitorUpsertOne) UpdateNewValues() *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(monitor.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Monitor.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *MonitorUpsertOne) Ignore() *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MonitorUpsertOne) DoNothing() *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MonitorCreate.OnConflict
// documentation for more info.
func (u *MonitorUpsertOne) Update(set func(*MonitorUpsert)) *MonitorUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MonitorUpsertOne) SetUpdatedAt(v time.Time) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateUpdatedAt() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMovieID sets the "movie_id" field.
func (u *MonitorUpsertOne) SetMovieID(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetMovieID(v)
	})
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateMovieID() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateMovieID()
	})
}

// SetCode sets the "code" field.
func (u *MonitorUpsertOne) SetCode(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateCode() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateCode()
	})
}

// SetTitle sets the "title" field.
func (u *MonitorUpsertOne) SetTitle(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateTitle() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateTitle()
	})
}

// SetCover sets the "cover" field.
func (u *MonitorUpsertOne) SetCover(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateCover() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateCover()
	})
}

// SetReleaseDate sets the "release_date" field.
func (u *MonitorUpsertOne) SetReleaseDate(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetReleaseDate(v)
	})
}

// UpdateReleaseDate sets the "release_date" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateReleaseDate() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateReleaseDate()
	})
}

// SetStatus sets the "status" field.
func (u *MonitorUpsertOne) SetStatus(v monitor.Status) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateStatus() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateStatus()
	})
}

// SetHash sets the "hash" field.
func (u *MonitorUpsertOne) SetHash(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateHash() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateHash()
	})
}

// SetTaskID sets the "task_id" field.
func (u *MonitorUpsertOne) SetTaskID(v int) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *MonitorUpsertOne) AddTaskID(v int) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateTaskID() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateTaskID()
	})
}

// ClearTaskID clears the value of the "task_id" field.
func (u *MonitorUpsertOne) ClearTaskID() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearTaskID()
	})
}

// SetNextCheckAt sets the "next_check_at" field.
func (u *MonitorUpsertOne) SetNextCheckAt(v time.Time) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetNextCheckAt(v)
	})
}

// UpdateNextCheckAt sets the "next_check_at" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateNextCheckAt() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateNextCheckAt()
	})
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (u *MonitorUpsertOne) ClearNextCheckAt() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearNextCheckAt()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *MonitorUpsertOne) SetLastCheckedAt(v time.Time) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateLastCheckedAt() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *MonitorUpsertOne) ClearLastCheckedAt() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetChecks sets the "checks" field.
func (u *MonitorUpsertOne) SetChecks(v int) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetChecks(v)
	})
}

// AddChecks adds v to the "checks" field.
func (u *MonitorUpsertOne) AddChecks(v int) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.AddChecks(v)
	})
}

// UpdateChecks sets the "checks" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateChecks() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateChecks()
	})
}

// SetError sets the "error" field.
func (u *MonitorUpsertOne) SetError(v string) *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *MonitorUpsertOne) UpdateError() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *MonitorUpsertOne) ClearError() *MonitorUpsertOne {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *MonitorUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MonitorCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MonitorUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *MonitorUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *MonitorUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// MonitorCreateBulk is the builder for creating many Monitor entities in bulk.
type MonitorCreateBulk struct {
	config
	err      error
	builders []*MonitorCreate
	conflict []sql.ConflictOption
}

// Save creates the Monitor entities in the database.
func (_c *MonitorCreateBulk) Save(ctx context.Context) ([]*Monitor, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Monitor, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MonitorCreateBulk) SaveX(ctx context.Context) []*Monitor {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MonitorCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Monitor.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.MonitorUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *MonitorCreateBulk) OnConflict(opts ...sql.ConflictOption) *MonitorUpsertBulk {
	_c.conflict = opts
	return &MonitorUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *MonitorCreateBulk) OnConflictColumns(columns ...string) *MonitorUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &MonitorUpsertBulk{
		create: _c,
	}
}

// MonitorUpsertBulk is the builder for "upsert"-ing
// a bulk of Monitor nodes.
type MonitorUpsertBulk struct {
	create *MonitorCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *MonitorUpsertBulk) UpdateNewValues() *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(monitor.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Monitor.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *MonitorUpsertBulk) Ignore() *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *MonitorUpsertBulk) DoNothing() *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the MonitorCreateBulk.OnConflict
// documentation for more info.
func (u *MonitorUpsertBulk) Update(set func(*MonitorUpsert)) *MonitorUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&MonitorUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *MonitorUpsertBulk) SetUpdatedAt(v time.Time) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateUpdatedAt() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetMovieID sets the "movie_id" field.
func (u *MonitorUpsertBulk) SetMovieID(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetMovieID(v)
	})
}

// UpdateMovieID sets the "movie_id" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateMovieID() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateMovieID()
	})
}

// SetCode sets the "code" field.
func (u *MonitorUpsertBulk) SetCode(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetCode(v)
	})
}

// UpdateCode sets the "code" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateCode() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateCode()
	})
}

// SetTitle sets the "title" field.
func (u *MonitorUpsertBulk) SetTitle(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateTitle() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateTitle()
	})
}

// SetCover sets the "cover" field.
func (u *MonitorUpsertBulk) SetCover(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetCover(v)
	})
}

// UpdateCover sets the "cover" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateCover() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateCover()
	})
}

// SetReleaseDate sets the "release_date" field.
func (u *MonitorUpsertBulk) SetReleaseDate(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetReleaseDate(v)
	})
}

// UpdateReleaseDate sets the "release_date" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateReleaseDate() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateReleaseDate()
	})
}

// SetStatus sets the "status" field.
func (u *MonitorUpsertBulk) SetStatus(v monitor.Status) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateStatus() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateStatus()
	})
}

// SetHash sets the "hash" field.
func (u *MonitorUpsertBulk) SetHash(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetHash(v)
	})
}

// UpdateHash sets the "hash" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateHash() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateHash()
	})
}

// SetTaskID sets the "task_id" field.
func (u *MonitorUpsertBulk) SetTaskID(v int) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetTaskID(v)
	})
}

// AddTaskID adds v to the "task_id" field.
func (u *MonitorUpsertBulk) AddTaskID(v int) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.AddTaskID(v)
	})
}

// UpdateTaskID sets the "task_id" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateTaskID() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateTaskID()
	})
}

// ClearTaskID clears the value of the "task_id" field.
func (u *MonitorUpsertBulk) ClearTaskID() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearTaskID()
	})
}

// SetNextCheckAt sets the "next_check_at" field.
func (u *MonitorUpsertBulk) SetNextCheckAt(v time.Time) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetNextCheckAt(v)
	})
}

// UpdateNextCheckAt sets the "next_check_at" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateNextCheckAt() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateNextCheckAt()
	})
}

// ClearNextCheckAt clears the value of the "next_check_at" field.
func (u *MonitorUpsertBulk) ClearNextCheckAt() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearNextCheckAt()
	})
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (u *MonitorUpsertBulk) SetLastCheckedAt(v time.Time) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetLastCheckedAt(v)
	})
}

// UpdateLastCheckedAt sets the "last_checked_at" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateLastCheckedAt() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateLastCheckedAt()
	})
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (u *MonitorUpsertBulk) ClearLastCheckedAt() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearLastCheckedAt()
	})
}

// SetChecks sets the "checks" field.
func (u *MonitorUpsertBulk) SetChecks(v int) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetChecks(v)
	})
}

// AddChecks adds v to the "checks" field.
func (u *MonitorUpsertBulk) AddChecks(v int) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.AddChecks(v)
	})
}

// UpdateChecks sets the "checks" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateChecks() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateChecks()
	})
}

// SetError sets the "error" field.
func (u *MonitorUpsertBulk) SetError(v string) *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *MonitorUpsertBulk) UpdateError() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *MonitorUpsertBulk) ClearError() *MonitorUpsertBulk {
	return u.Update(func(s *MonitorUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *MonitorUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the MonitorCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for MonitorCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *MonitorUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
