// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ppxb/miyabi/internal/ent/viewedmovie"
)

// ViewedMovie is the model entity for the ViewedMovie schema.
type ViewedMovie struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// MovieID holds the value of the "movie_id" field.
	MovieID      string `json:"movie_id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ViewedMovie) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case viewedmovie.FieldID:
			values[i] = new(sql.NullInt64)
		case viewedmovie.FieldMovieID:
			values[i] = new(sql.NullString)
		case viewedmovie.FieldCreatedAt, viewedmovie.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ViewedMovie fields.
func (_m *ViewedMovie) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case viewedmovie.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case viewedmovie.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case viewedmovie.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case viewedmovie.FieldMovieID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field movie_id", values[i])
			} else if value.Valid {
				_m.MovieID = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ViewedMovie.
// This includes values selected through modifiers, order, etc.
func (_m *ViewedMovie) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ViewedMovie.
// Note that you need to call ViewedMovie.Unwrap() before calling this method if this ViewedMovie
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ViewedMovie) Update() *ViewedMovieUpdateOne {
	return NewViewedMovieClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ViewedMovie entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ViewedMovie) Unwrap() *ViewedMovie {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ViewedMovie is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ViewedMovie) String() string {
	var builder strings.Builder
	builder.WriteString("ViewedMovie(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("movie_id=")
	builder.WriteString(_m.MovieID)
	builder.WriteByte(')')
	return builder.String()
}

// ViewedMovies is a parsable slice of ViewedMovie.
type ViewedMovies []*ViewedMovie
